Project/sources/ETOS/ETOS.WebUI/ViewModels/ContractorViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

using ETOS.Core.DTO;
using System.Web.Mvc;

namespace ETOS.WebUI.ViewModels
{
    /// <summary>
    /// ViewModel для поиска подрядчика
    /// </summary>
    public class ContractorViewModel
    {
        /// <summary>
        /// id заявки
        /// </summary>
		[ScaffoldColumn(false)]
        public int RequestId { get; set; }

        /// <summary>
        /// Адрес точки назначения
        /// </summary>
        public string DestinationAddress;

        /// <summary>
        /// Адрес точки отправки
        /// </summary>
        public string DepartureAddress;

        /// <summary>
        /// Список подрядчиков с информацией
        /// </summary>
        public List<DtoContractorInfo> contractors;

        /// <summary>
        /// Расстояние между пунктами
        /// </summary>
        public float Mileage { get; set; }


		public decimal Price { get; set; }

       /// <summary>
       /// Выбраный подрядчик
       /// </summary>
        public int SelectedContractorId { get; set; }

        /// <summary>
        /// Информация об автомобиле
        /// </summary>
        public string Comment { get; set; }

        /// <summary>
        ///  ошибки
        /// </summary>
        public List<string> errors { get; set; }
    }

	/// <summary>
	/// Модель представления для подрядчика.
	/// </summary>
	public class ContractorInfoViewModel
	{
		/// <summary>
		/// Код подрядчика.
		/// </summary>
		[ScaffoldColumn(false)]
		public int Id { get; set; }

		/// <summary>
		/// Название фирмы-подрядчика.
		/// </summary>
		[Required(ErrorMessage = "Пожалуйста, укажите название фирмы.")]
		[MaxLength(100, ErrorMessage = "Длина названия фирмы не должна превышать 100 символов!")]
		[Display(Name = "Название фирмы")]
		public string Name { get; set; }

		/// <summary>
		/// Номер телефона подрядчика.
		/// </summary>
		[Required(ErrorMessage = "Пожалуйста, укажите номер телефона фирмы.")]
		[MaxLength(16, ErrorMessage = "Длина номера телефона не должна превышать 16 символов!")]
		[Display(Name = "Номер телефона")]
		public string Phone { get; set; }

		/// <summary>
		/// Тариф подрядчика за 1 км.
		/// </summary>
		[Required(ErrorMessage = "Пожалуйста, укажите тариф подрядчика за 1 км.")]
		[Display(Name = "Тариф за 1 км.")]
		public decimal Tariff { get; set; }
	}

	/// <summary>
	/// Модель представления для списка подрядчиков.
	/// </summary>
	public class ContractorListViewModel
	{
		public IEnumerable<ContractorInfoViewModel> Contractors { get; set; }
	}
}

Project/sources/ETOS/ETOS.WebUI/Controllers/ContractorController.cs
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;

using ETOS.Core.DTO;
using ETOS.Core.Services.Abstract;
using ETOS.WebUI.ViewModels;
using ETOS.WebUI.RequestPriceCalculator;

namespace ETOS.WebUI.Controllers
{
	/// <summary>
	/// Контроллер, обеспечивающий работу с подрядчиками на уровне представления.
	/// </summary>
	[Authorize]
    public class ContractorController : Controller
    {
        #region Fields

        IRequestService _requestService;
        ILocationService _locationService;
        IContractorService _contractorService;

        #endregion 

        #region Constructor

        public ContractorController(IRequestService reqService, ILocationService locService, IContractorService contractorService)
        {
            _requestService = reqService;
            _locationService = locService;
            _contractorService = contractorService;
        }

        #endregion 

        #region Methods

        /// <summary>
        /// Get-версия метода, возвращающая представление с подрядчиками подходящими данной заявке
        /// </summary>        
        [HttpGet]
        public ViewResult Select(int id)
        {
            var model = new ContractorViewModel();
            model.errors = new List<string>();
            var error = "";
            var request = new DtoRequest();
            if (!_requestService.GetRequestById(id, out request, out error))
            {
                model.errors.Add(error);
            }

            model.RequestId = request.Id;
            model.Mileage = request.Mileage;

            int? DeparturePointId = null;
         
            if (request.DeparturePointId != null)
            {
                DeparturePointId = request.DeparturePointId;
                model.DepartureAddress = _locationService.GetPOIById((int)DeparturePointId).Name;
            }
            else
            {
                model.DepartureAddress = request.DepartureAddress;
            }

            model.contractors = _contractorService.GetAllContractors();

            if (model.contractors == null || model.contractors.Count == 0)
            {
                model.errors.Add("Не найдено подходящих вариантов для данной поездки");
            }

			var requestPriceCalculator = new RequestPriceCalculatingServiceClient();
            
			// заполняем цену поездки для каждого подрядчика 
            foreach (var contractor in model.contractors)
            {
				contractor.TotalPrice = requestPriceCalculator.CalculateRequestPrice(model.Mileage, contractor.Tariff);
            }

			requestPriceCalculator.Close();

            return View(model);
        }

        /// <summary>
        /// Get-версия метода, возвращающая представление для создания новой заявки.
        /// </summary>
        [HttpPost]
        public ActionResult Select(ContractorViewModel model)
        {
            var error = "";
            if (model.errors == null) model.errors = new List<string>();

            if (!_contractorService.SetContractorForRequest(out error, model.SelectedContractorId, model.RequestId, model.Comment))
            {
                model.errors.Add(error);
                return View(model);
            }
            return RedirectToAction("Index", "Request");
        }

		public ViewResult Index()
		{
			var model = new ContractorListViewModel
			{
				Contractors = _contractorService.GetContractorsList()
					.Select(c => new ContractorInfoViewModel
					{
						Id = c.Id,
						Name = c.Name,
						Phone = c.Phone,
						Tariff = c.Tariff
					})
			};

			return View(model);
		}

		public ViewResult Create()
		{
			ViewBag.Title = "Добавление нового подрядчика";

			return View("Edit", new ContractorInfoViewModel { Id = 0 });
		}

		public ViewResult Edit(int contractorId)
		{
			var contractorDto = _contractorService.GetContractor(contractorId);

			if (contractorDto != null)
			{
				var model = new ContractorInfoViewModel
				{
					Id = contractorDto.Id,
					Name = contractorDto.Name,
					Phone = contractorDto.Phone,
					Tariff = contractorDto.Tariff
				};

				ViewBag.Title = "Редактирование данных подрядчика";

				return View(model);
			}

			return View("_Error");
		}

		public ActionResult Save(ContractorInfoViewModel model)
		{
			if (ModelState.IsValid)
			{
				var contractor = new DtoContractor
				{
					Id = model.Id,
					Name = model.Name,
					Phone = model.Phone,
					Tariff = model.Tariff
				};

				_contractorService.SaveContractor(contractor);

				return RedirectToAction("Index");
			}
			else
			{
				if (model.Id > 0)
				{
					return RedirectToAction("Edit", new { contractorId = model.Id });
				}
				else
				{
					return RedirectToAction("Create");
				}
			}
		}
		
		public ActionResult Remove(int contractorId)
		{
			if (contractorId > 0)
			{
				_contractorService.RemoveContractor(contractorId);

				return RedirectToAction("Index");
			}
			else
			{
				return View("_Error");
			}
		}
		
		#endregion
	}
}

Project/sources/ETOS/ETOS.WebUI/Views/Contractor/Edit.cshtml
@model ContractorInfoViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Save", "Contractor", FormMethod.Post, new { @class = "form-horizontal" }))
{
    if (!ViewData.ModelState.IsValid)
    {
        <div class="form-group">
            @Html.ValidationSummary(false, "", new { @class = "col-md-4 col-md-offset-4 alert alert-danger" })
        </div>
    }
    <legend><h4>@ViewBag.Title</h4></legend>
    <fieldset>
        <div class="form-group">
            @Html.HiddenFor(m => m.Id)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            <div class="col-md-4">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-md " })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Phone)
            <div class="col-md-4">
                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control input-md", @placeholder = "Например: 21-34-45" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Tariff)
            <div class="col-md-4">
                @Html.TextBoxFor(m => m.Tariff, new { @class = "form-control input-md ", @placeholder = "Например: 10,50" })
            </div>
        </div>
    </fieldset>
    <div class="form-group media-right">
        <input type="submit" class="btn btn-success btn-sm" value="Сохранить" />
    </div>
}

@section scripts
{
    <script src="~/Scripts/jquery.mask.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $('#Phone').mask('99-99-99');
            $('#Tariff').mask("#.##0,00", { reverse: true })
        });
    </script>
}

Project/sources/ETOS/ETOS.WebUI/Views/Contractor/Index.cshtml
@model ContractorListViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Перечень подрядчиков";
}
<div>
    <table class="table table-responsive">
        <thead>
            <tr>
                <th>Код подрядчика</th>
                <th>Название фирмы</th>
                <th>Номер телефона</th>
                <th>Тариф за 1 км</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Contractors.Count() == 0)
            {
                <tr>
                    <td colspan="5" class="text-center">Подрядчики отсутствуют</td>
                </tr>
            }
            else
            {
                foreach (var contractor in Model.Contractors)
                {
                    <tr>
                        <td>@contractor.Id</td>
                        <td>@contractor.Name</td>
                        <td>@contractor.Phone</td>
                        <td>@contractor.Tariff</td>
                        <td>
                            @Html.ActionLink("Подробнее", "GetContractorDetails", new { @contractorId = contractor.Id }, new { @class = "btn btn-info btn-xs" })
                            @Html.ActionLink("Редактировать", "Edit", new { @contractorId = contractor.Id }, new { @class = "btn btn-primary btn-xs" })
                            @Html.ActionLink("Удалить", "Remove", new { @contractorId = contractor.Id }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>
    @Html.ActionLink("Добавить подрядчика", "Create", null , new { @class = "btn btn-primary"})
</div>

Project/sources/ETOS/ETOS.WebUI/Views/Contractor/Select.cshtml
@model ContractorViewModel
@{
    ViewBag.Title = "Поиск и назначение подрядчика";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <h2>Подходящие варианты:</h2>
    <div>
        <table class="table">
            <tr>
                <td align="right">Откуда:</td>
                <td align="left">@Model.DepartureAddress</td>
            </tr>
            <tr>
                <td align="right">Куда:</td>
                <td align="left">@Model.DestinationAddress</td>
            </tr>
            <tr>
                <td align="right">Расстояние:</td>
                <td align="left">@Model.Mileage км</td>
            </tr>
        </table>
    </div>
    <br />

    @if (Model.errors.Count == 0)
    {
        using (Html.BeginForm("Select", "Contractor", FormMethod.Post))
        {
            <table class="table">
                <tbody>
                    <tr>
                        <td align="center">Название такси</td>
                        <td align="center">Телефон</td>
                        <td align="center">Цена за 1 км</td>
                        <td align="center">Итоговая стоимость поездки</td>
                        <td align="center">Выбор</td>
                    </tr>

                    @foreach (var contractor in Model.contractors)
                    {
                        <tr>
                            <td align="center">@contractor.Name</td>
                            <td align="center">@contractor.Phone</td>
                            <td align="center">@contractor.Tariff</td>
                            <td align="center">@contractor.TotalPrice руб</td>
                            <td>
                                @*@Html.RadioButtonFor(m => m.SelectedContractorId, new { contractor.Id })*@
                                <input type="radio" value="@contractor.Id" name="SelectedContractorId" />
                            </td>
                        </tr>
                    }
                <tbody>
            </table>
            <input type="hidden" value="@Model.RequestId" name="requestId" />
            <div class="form-group">
                <div class="col-md-12">
                    <input type="text" value="Цвет авто: Розовый, Модель: БЕЛАЗ 7555, Номер авто: о321па" name="Comment" width="600" /><br /><br />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Выбрать" />
                </div>
            </div>
        }
    }
    else
    {
        foreach (var error in Model.errors)
        {
            <div class="alert alert-danger"> @error </div><br />
        }
    }